[project]
name = "panda-utils"
version = "0.1.0"
description = "Pointcloud utils and control for the franka panda robot"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mani_skill",
    "numpy",
    "open3d",
    "termcolor",
    "h5py",
    "torch",
    "pytest"
]

